### ISSUE TITLE
Some Issue

### ISSUE THREAD

**Issue by ARandom12** [Zolika1351/iv-sdk#1]
I'm encountering an issue, firstly, the Pools with Natives are not working for whatever reason(for specific models only). And secondly, the Scripting Functions starts with `_TASK, TASK` makes the game crash.
Maybe, I'm doing it in a wrong way, can you suggest how should I make those Natives work.

**Comment by Zolika1351** [comment]
Fixed by f6e9d7b089f38d62686fd30bb00fd0f770b8203f
